[package]
name = "neuro"
version = "0.4.0"
description = "A Motoko package for basic staking and neuron management."
repository = "https://github.com/jesssekeogh/neuro"
keywords = [ "neuro", "neuron", "nns", "stake", "icp" ]
license = "MIT"

[dependencies]
sha2 = "0.0.6"
encoding = "https://github.com/aviate-labs/encoding.mo#master@2711d18727e954b11afc0d37945608512b5fbce2"
account-identifier = "1.0.2"